version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    env_file: 
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

